#! /bin/sh

### BEGIN INIT INFO
# Provides:          sickbeard
# Required-Start:    $local_fs $network $remote_fs
# Required-Stop:     $local_fs $network $remote_fs
# Should-Start:      $NetworkManager
# Should-Stop:       $NetworkManager
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts instance of Sick Beard
# Description:       starts instance of Sick Beard using start-stop-daemon
### END INIT INFO

############### EDIT ME ##################
# Path to store PID file
PID_FILE=/var/run/sickbeard/sickbeard.pid
PID_PATH=/var/run/sickbeard

# script name
NAME=sickbeard

# startup args
DAEMON_OPTS=" SickBeard.py -q --daemon --pidfile=${PID_FILE}"

PIDFILE=/var/run/sickbeard.pid
SETTINGS_LOADED=FALSE
RUN_AS=sickbeard
DAEMON=/usr/bin/python
APP_PATH=/opt/sickbeard
############### END EDIT ME ##################

test -x $DAEMON || exit 0

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

set -e

if [ ! -d $PID_PATH ]; then
    mkdir -p $PID_PATH
fi

chown -R $RUN_AS:users $PID_PATH

if [ -e $PID_FILE ]; then
    PID=`cat $PID_FILE`
    if ! kill -0 $PID > /dev/null 2>&1; then
        echo "Removing stale $PID_FILE"
        rm $PID_FILE
    fi
fi

is_running()
{
    if [ ! -e $PID_FILE ]; then
        return 1
    fi
    return 0
}

case "$1" in
    start)
        echo "Starting $DESC"
        cd $APP_PATH
        #/usr/bin/git stash
        start-stop-daemon -d $APP_PATH -c $RUN_AS --start --pidfile $PID_FILE --exec $DAEMON -- $DAEMON_OPTS
        ;;

    stop)
        if is_running; then
            echo "Stopping $DESC"
            start-stop-daemon --stop --pidfile $PID_FILE --retry 15
        fi
        ;;

    restart|force-reload)stop)
        if is_running; then
            echo "Stopping $DESC"
            start-stop-daemon --stop --pidfile $PID_FILE --retry 15
        fi
        echo "Restarting $DESC"
        start-stop-daemon -d $APP_PATH -c $RUN_AS --start --pidfile $PID_FILE --exec $DAEMON -- $DAEMON_OPTS
        ;;

    status)
        status_of_proc -p $PID_FILE "$DAEMON" "$NAME"
        ;;

    *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|status|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
