#! /bin/sh

### BEGIN INIT INFO
# Provides:          sickbeard
# Required-Start:    $local_fs $network $remote_fs
# Required-Stop:     $local_fs $network $remote_fs
# Should-Start:      $NetworkManager
# Should-Stop:       $NetworkManager
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts instance of CouchPotato
# Description:       starts instance of CouchPotato using start-stop-daemon
### END INIT INFO

############### BEGIN EDIT ME ################
RUN_GRP=users
RUN_AS=sickbeard
APP_PATH=/opt/sickbeard
DAEMON=$APP_PATH/SickBeard.py
PID_FILE=/var/run/sickbeard/sickbeard.pid
PID_PATH=$(dirname $PID_FILE)
NAME=sickbeard
DESC=sickbeard
DAEMON_OPTS=" --daemon --pidfile=${PID_FILE}"
ISRUN=0
############### END EDIT ME ##################

# Get lsb functions
. /lib/lsb/init-functions

# Create PID directory if not exist and ensure the Sickbeard user can write to it
if [ ! -d $PID_PATH ]; then
    mkdir -p $PID_PATH
    chown $RUN_AS $PID_PATH
fi

if [ -e $PID_FILE ]; then
    PID=`cat $PID_FILE`
    if ! kill -0 $PID > /dev/null 2>&1; then
        echo "Removing stale $PID_FILE"
        rm $PID_FILE
    fi
fi

is_running() {
  if [ ! -e $PID_FILE ]; then
    return 1
  fi
  return 0
}


start() {
  if ! is_running; then
    echo "Starting $DESC"
    #start-stop-daemon -c $RUN_AS --start --exec $DAEMON -- $DAEMON_OPTS
    /usr/bin/python $DAEMON $DAEMON_OPTS
    echo "start-stop-daemon -c $RUN_AS --start --exec $DAEMON -- $DAEMON_OPTS"
  else
    echo "$DESC is running"
  fi
}

stop() {
  if is_running; then
    echo "Stopping $DESC"
    start-stop-daemon --stop --pidfile $PID_FILE --retry 15
  fi
}

restart() {
  if is_running; then
    stop
  fi
  echo "Restarting $DESC"
  start
}

master() {
  if is_running; then
    ISRUN=1
    stop
  fi
  cd $APP_PATH
  sudo -u $RUN_AS git stash
  sudo -u $RUN_AS git checkout master
  #chown $RUN_AS:$RUN_GRP $APP_PATH -R
  #chmod 775 $APP_PATH -R
  #git stash
  #if [ "$ISRUN" == 1 ]; then
  #  start
  #fi
}

develop() {
  if is_running; then
    ISRUN=1
    stop
  fi
  cd $APP_PATH
  sudo -u $RUN_AS git stash
  sudo -u $RUN_AS git checkout development
  #chown $RUN_AS:$RUN_GRP $APP_PATH -R
  #chmod 775 $APP_PATH -R
  #git stash
  #if [ "$ISRUN" == 1 ]; then
  #  start
  #fi
}

swap() {
  if is_running; then
    ISRUN=1
    stop
  fi
  if [ -d $APP_PATH ]; then
    rm -Rf $APP_PATH
  fi
  #sudo -u $RUN_AS git clone $1 -b $2 $APP_PATH
  sudo -u $RUN_AS git clone "$1" -b "$2" $APP_PATH
  sudo -u $RUN_AS echo 'git_path = "/usr/bin/git"' > "${APP_PATH}/config.ini"
  #chown $RUN_AS:$RUN_GRP $APP_PATH -R
  #chmod 775 $APP_PATH -R
  #cd $APP_PATH
  #git stash
  #if [ "$ISRUN" == 1 ]; then
  #  start-stop-daemon -c $RUN_AS --start --exec $DAEMON -- $DAEMON_OPTS
  #fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  swap)
    swap $2 $3
    ;;
  master)
    master
    ;;
  develop)
    develop
    ;;
  retart)
    stop
    start
    ;;
  status)
    status_of_proc -p $PID_FILE "$DAEMON" "$NAME"
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac

exit 0
