#!/bin/sh
#
set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_SICKBEARD_APP_PATH="/opt/sickbeard/"
OMV_SICKBEARD_DATA_PATH="/var/opt/sickbeard"
OMV_SICKBEARD_APP_PATH2="/opt/sickbeard2/"
OMV_SICKBEARD_DATA_PATH2="/var/opt/sickbeard2"
OMV_SICKBEARD_XPATH="/config/services/sickbeard"

case "$1" in
    purge)
        omv_config_delete OMV_SICKBEARD_XPATH

        if [ -d $OMV_SICKBEARD_APP_PATH ]; then
            find $OMV_SICKBEARD_APP_PATH -mindepth 1 -delete
        fi

        if [ -d $OMV_SICKBEARD_APP_PATH2 ]; then
            find $OMV_SICKBEARD_APP_PATH2 -mindepth 1 -delete
        fi

        if [ -d $OMV_SICKBEARD_DATA_PATH ]; then
            find $OMV_SICKBEARD_DATA_PATH -mindepth 1 -delete
        fi

        if [ -d $OMV_SICKBEARD_DATA_PATH2 ]; then
            find $OMV_SICKBEARD_DATA_PATH2 -mindepth 1 -delete
        fi


        if [ -f "/var/run/sickbeard/sickbeard.pid" ]; then
            PID=`cat /var/run/sickbeard/sickbeard.pid`
            kill -0 $PID 2>/dev/null;

            if [ $? -eq 0 ]; then
                kill -9 $PID;
            fi
        fi

        if [ -f "/var/run/sickbeard/sickbeard2.pid" ]; then
            PID=`cat /var/run/sickbeard/sickbeard2.pid`;
            kill -0 $PID 2>/dev/null;

            if [ $? -eq 0 ]; then
                kill -9 $PID;
            fi
        fi

        if [ -f "/etc/init.d/sickbeard2" ]; then
            update-rc.d sickbeard2 disable;
            rm -Rf /etc/init.d/sickbeard2
        fi

        rm -Rf /var/run/sickbeard & >/dev/null
        rm -Rf /opt/sickbeard & >/dev/null
        rm -Rf /opt/sickbeard2 & >/dev/null

        omv_config_delete "//services/sickbeard"

        if [ -d "/opt/sickbeard" ]; then
            rm -Rf /opt/sickbeard/autoProcessTV & >/dev/null
            rm -Rf /opt/sickbeard/* & >/dev/null
            rm -Rf /opt/sickbeard/.git & >/dev/null
            rm -Rf /opt/sickbeard/.gitignore & >/dev/null
        fi

        if [ -d "/opt/sickbeard2" ]; then
            rm -Rf /opt/sickbeard2/* & >/dev/null
            rm -Rf /opt/sickbeard2/.git & >/dev/null
            rm -Rf /opt/sickbeard2/.gitignore & >/dev/null
        fi

        userdel -rf sickbeard

        if [ ! -d /opt ]; then
            mkdir /opt
            chmod 775 /opt
        fi
    ;;

        remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
