#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
    if ! grep -q "^sickbeard:" /etc/passwd; then
        echo "Adding sickbeard user..."
        useradd --create-home --groups users --no-user-group --shell /usr/sbin/nologin sickbeard
    else
        echo "sickbeard user already exists."
    fi

    if [ -e /var/run/sickbeard ]; then
        echo "Cleaning old pid file..."
        rm /var/run/sickbeard -Rf
    fi

    chmod 775 /opt
    chown sickbeard:users /opt
    chown sickbeard:users /etc/init.d/sickbeard
    insserv -d sickbeard
    if ! omv_config_exists "/config/services/sickbeard/sb_repo"; then
        echo "Initial configuration."
        object="<enable>0</enable>"
        object="${object}<showtab>0</showtab>"
        object="${object}<sb_branch>0</sb_branch>"
        object="${object}<sb_repo></sb_repo>"
        omv_config_add_element "/config/services" "sickbeard" "${object}" true
    fi
    update-rc.d sickbeard disable
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
    echo "postinst called with unknown argument" >&2
    exit 1
    ;;
esac

exit 0