#!/bin/sh
#
set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_SICKBEARD1_APP_PATH="/opt/sickbeard/"
OMV_SICKBEARD1_DATA_PATH="/var/opt/sickbeard"
OMV_SICKBEARD2_APP_PATH="/opt/sickbeard2/"
OMV_SICKBEARD2_DATA_PATH="/var/opt/sickbeard2"
OMV_SICKBEARD_XPATH="/config/services/sickbeard"

case "$1" in
    purge)
        systemctl stop sickbeard.service

        if [ -f /etc/systemd/system/sickbeard2.service ]; then
            systemctl stop sickbeard2.service
            rm -Rf /etc/systemd/system/sickbeard2.service
        fi

        omv_config_delete OMV_SICKBEARD_XPATH

        if [ -d $OMV_SICKBEARD1_APP_PATH ]; then
            find $OMV_SICKBEARD1_APP_PATH -mindepth 1 -delete
        fi

        if [ -d $OMV_SICKBEARD2_APP_PATH ]; then
            find $OMV_SICKBEARD2_APP_PATH -mindepth 1 -delete
        fi

        if [ -d $OMV_SICKBEARD1_DATA_PATH ]; then
            find $OMV_SICKBEARD1_DATA_PATH -mindepth 1 -delete
        fi

        if [ -d $OMV_SICKBEARD2_DATA_PATH ]; then
            find $OMV_SICKBEARD2_DATA_PATH -mindepth 1 -delete
        fi


        if [ -f "/var/run/sickbeard/sickbeard.pid" ]; then
            start-stop-daemon --stop --pidfile /var/run/sickbeard/sickbeard.pid --retry 15 --oknodo > /dev/null 2>&1
        #    PID=`cat /var/run/sickbeard/sickbeard.pid`
        #    kill -0 $PID 2>/dev/null;

        #    if [ $? -eq 0 ]; then
        #        kill -9 $PID;
        #    fi
        fi

        if [ -f "/var/run/sickbeard/sickbeard2.pid" ]; then
            start-stop-daemon --stop --pidfile /var/run/sickbeard/sickbeard2.pid --retry 15 --oknodo > /dev/null 2>&1
        #    PID=`cat /var/run/sickbeard/sickbeard2.pid`;
        #    kill -0 $PID 2>/dev/null;

        #    if [ $? -eq 0 ]; then
        #        kill -9 $PID;
        #    fi
        fi

        if [ -f "/etc/init.d/sickbeard2" ]; then
            update-rc.d sickbeard2 disable;
            rm -Rf /etc/init.d/sickbeard2
        fi

        rm -Rf /var/run/sickbeard & >/dev/null
        rm -Rf /opt/sickbeard & >/dev/null
        rm -Rf /opt/sickbeard2 & >/dev/null
        rm -Rf /var/opt/sickbeard & >/dev/null
        rm -Rf /var/opt/sickbeard2 & >/dev/null
        rm -f /etc/default/sickbeard & >/dev/null
        rm -f /etc/default/sickbeard2 & >/dev/null

        omv_config_delete "//services/sickbeard"

        if [ -d "/opt/sickbeard" ]; then
            rm -Rf /opt/sickbeard/autoProcessTV & >/dev/null
            rm -Rf /opt/sickbeard/* & >/dev/null
            rm -Rf /opt/sickbeard/.git & >/dev/null
            rm -Rf /opt/sickbeard/.gitignore & >/dev/null
        fi

        if [ -d "/opt/sickbeard2" ]; then
            rm -Rf /opt/sickbeard2/* & >/dev/null
            rm -Rf /opt/sickbeard2/.git & >/dev/null
            rm -Rf /opt/sickbeard2/.gitignore & >/dev/null
        fi

        if getent passwd sickbeard >/dev/null 2>&1; then
            userdel -rf sickbeard
        fi

        if [ ! -d /opt ]; then
            mkdir /opt
            chmod 775 /opt
        fi
    ;;

        remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
