#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_SICKBEARD1_APP_PATH="/opt/sickbeard"
OMV_SICKBEARD1_OLD_DATA_PATH="/home/sickbeard/.sickbeard"
OMV_SICKBEARD2_OLD_DATA_PATH="/home/sickbeard/.sickbeard2"
OMV_SICKBEARD1_DATA_PATH="/var/opt/sickbeard"
OMV_SICKBEARD2_DATA_PATH="/var/opt/sickbeard2"
OMV_SICKBEARD_USER="sickbeard"
OMV_SICKBEARD_GROUP="users"

case "$1" in
    configure)
        SERVICE_XPATH_NAME="sickbeard"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_element "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "ssl" "0"
            omv_config_add_element "${SERVICE_XPATH}" "ppass" "0"
            omv_config_add_element "${SERVICE_XPATH}" "repo" "Please choose a repository"
            omv_config_add_element "${SERVICE_XPATH}" "branch" "Please choose a branch"
            omv_config_add_element "${SERVICE_XPATH}" "repo2" "Please choose a repository"
            omv_config_add_element "${SERVICE_XPATH}" "branch2" "Please choose a branch"
            omv_config_add_element "${SERVICE_XPATH}" "show_tab" "0"
        fi

        if ! getent passwd sickbeard >/dev/null 2>&1; then
            adduser --quiet \
                    --system \
                    --ingroup $OMV_SICKBEARD_GROUP \
                    --no-create-home \
                    --disabled-password \
                    $OMV_SICKBEARD_USER
        fi

        if [ -e $OMV_SICKBEARD1_OLD_DATA_PATH ]; then
            if [ ! -e $OMV_SICKBEARD1_DATA_PATH ]; then
                cp -Ra $OMV_SICKBEARD1_OLD_DATA_PATH/* $OMV_SICKBEARD1_DATA_PATH
                #rm -Rf OMV_SICKBEARD1_OLD_DATA_PATH
            fi
        fi

        if [ -e $OMV_SICKBEARD2_OLD_DATA_PATH ]; then
            if [ ! -e $OMV_SICKBEARD2_DATA_PATH ]; then
                cp -Ra $OMV_SICKBEARD2_OLD_DATA_PATH/* $OMV_SICKBEARD2_DATA_PATH
            fi
        fi

        chown $OMV_SICKBEARD_USER:$OMV_SICKBEARD_GROUP $OMV_SICKBEARD1_APP_PATH
        chown $OMV_SICKBEARD_USER:$OMV_SICKBEARD_GGOUP $OMV_SICKBEARD1_DATA_PATH -R

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
